/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeAResourcePrincipalRouteImport } from './routes/become-a-resource-principal'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LearningHubRouteImport } from './routes/learning-hub'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SponsorshipsRouteImport } from './routes/sponsorships'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as ExpertsIndexRouteImport } from './routes/experts.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as LearningPathsIndexRouteImport } from './routes/learning-paths.index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as ResourcePrincipalsIndexRouteImport } from './routes/resource-principals.index'
import { Route as ResourcePrincipalsSlugRouteImport } from './routes/resource-principals.$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify.$certificateId'
import { Route as WebinarsIndexRouteImport } from './routes/webinars.index'
import { Route as WebinarsSlugRouteImport } from './routes/webinars.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAResourcePrincipalRoute =
  BecomeAResourcePrincipalRouteImport.update({
    id: '/become-a-resource-principal',
    path: '/become-a-resource-principal',
    getParentRoute: () => rootRouteImport,
  } as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubRoute = LearningHubRouteImport.update({
  id: '/learning-hub',
  path: '/learning-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipsRoute = SponsorshipsRouteImport.update({
  id: '/sponsorships',
  path: '/sponsorships',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsIndexRoute = ExpertsIndexRouteImport.update({
  id: '/experts/',
  path: '/experts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsIndexRoute = LearningPathsIndexRouteImport.update({
  id: '/learning-paths/',
  path: '/learning-paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcePrincipalsIndexRoute = ResourcePrincipalsIndexRouteImport.update({
  id: '/resource-principals/',
  path: '/resource-principals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcePrincipalsSlugRoute = ResourcePrincipalsSlugRouteImport.update({
  id: '/resource-principals/$slug',
  path: '/resource-principals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)
const WebinarsIndexRoute = WebinarsIndexRouteImport.update({
  id: '/webinars/',
  path: '/webinars/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebinarsSlugRoute = WebinarsSlugRouteImport.update({
  id: '/webinars/$slug',
  path: '/webinars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-resource-principal': typeof BecomeAResourcePrincipalRoute
  '/certificates': typeof CertificatesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/learning-hub': typeof LearningHubRoute
  '/my-learning': typeof MyLearningRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/resource-principals/$slug': typeof ResourcePrincipalsSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/webinars/$slug': typeof WebinarsSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/experts/': typeof ExpertsIndexRoute
  '/learning-paths/': typeof LearningPathsIndexRoute
  '/media/': typeof MediaIndexRoute
  '/resource-principals/': typeof ResourcePrincipalsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/webinars/': typeof WebinarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-resource-principal': typeof BecomeAResourcePrincipalRoute
  '/certificates': typeof CertificatesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/learning-hub': typeof LearningHubRoute
  '/my-learning': typeof MyLearningRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/resource-principals/$slug': typeof ResourcePrincipalsSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/webinars/$slug': typeof WebinarsSlugRoute
  '/community': typeof CommunityIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/experts': typeof ExpertsIndexRoute
  '/learning-paths': typeof LearningPathsIndexRoute
  '/media': typeof MediaIndexRoute
  '/resource-principals': typeof ResourcePrincipalsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/webinars': typeof WebinarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-a-resource-principal': typeof BecomeAResourcePrincipalRoute
  '/certificates': typeof CertificatesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/learning-hub': typeof LearningHubRoute
  '/my-learning': typeof MyLearningRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sponsorships': typeof SponsorshipsRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/resource-principals/$slug': typeof ResourcePrincipalsSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/webinars/$slug': typeof WebinarsSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/experts/': typeof ExpertsIndexRoute
  '/learning-paths/': typeof LearningPathsIndexRoute
  '/media/': typeof MediaIndexRoute
  '/resource-principals/': typeof ResourcePrincipalsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/webinars/': typeof WebinarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-resource-principal'
    | '/certificates'
    | '/cookie-policy'
    | '/dashboard'
    | '/disclaimer'
    | '/learning-hub'
    | '/my-learning'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/sponsorships'
    | '/terms'
    | '/verification'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/resource-principals/$slug'
    | '/verify/$certificateId'
    | '/webinars/$slug'
    | '/community/'
    | '/courses/'
    | '/experts/'
    | '/learning-paths/'
    | '/media/'
    | '/resource-principals/'
    | '/resources/'
    | '/webinars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-resource-principal'
    | '/certificates'
    | '/cookie-policy'
    | '/dashboard'
    | '/disclaimer'
    | '/learning-hub'
    | '/my-learning'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/sponsorships'
    | '/terms'
    | '/verification'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/resource-principals/$slug'
    | '/verify/$certificateId'
    | '/webinars/$slug'
    | '/community'
    | '/courses'
    | '/experts'
    | '/learning-paths'
    | '/media'
    | '/resource-principals'
    | '/resources'
    | '/webinars'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/become-a-resource-principal'
    | '/certificates'
    | '/cookie-policy'
    | '/dashboard'
    | '/disclaimer'
    | '/learning-hub'
    | '/my-learning'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/sponsorships'
    | '/terms'
    | '/verification'
    | '/courses/$slug'
    | '/learn/$slug'
    | '/resource-principals/$slug'
    | '/verify/$certificateId'
    | '/webinars/$slug'
    | '/community/'
    | '/courses/'
    | '/experts/'
    | '/learning-paths/'
    | '/media/'
    | '/resource-principals/'
    | '/resources/'
    | '/webinars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BecomeAResourcePrincipalRoute: typeof BecomeAResourcePrincipalRoute
  CertificatesRoute: typeof CertificatesRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LearningHubRoute: typeof LearningHubRoute
  MyLearningRoute: typeof MyLearningRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SponsorshipsRoute: typeof SponsorshipsRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  ResourcePrincipalsSlugRoute: typeof ResourcePrincipalsSlugRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
  WebinarsSlugRoute: typeof WebinarsSlugRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ExpertsIndexRoute: typeof ExpertsIndexRoute
  LearningPathsIndexRoute: typeof LearningPathsIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  ResourcePrincipalsIndexRoute: typeof ResourcePrincipalsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  WebinarsIndexRoute: typeof WebinarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-resource-principal': {
      id: '/become-a-resource-principal'
      path: '/become-a-resource-principal'
      fullPath: '/become-a-resource-principal'
      preLoaderRoute: typeof BecomeAResourcePrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-hub': {
      id: '/learning-hub'
      path: '/learning-hub'
      fullPath: '/learning-hub'
      preLoaderRoute: typeof LearningHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorships': {
      id: '/sponsorships'
      path: '/sponsorships'
      fullPath: '/sponsorships'
      preLoaderRoute: typeof SponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/': {
      id: '/experts/'
      path: '/experts'
      fullPath: '/experts/'
      preLoaderRoute: typeof ExpertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths/': {
      id: '/learning-paths/'
      path: '/learning-paths'
      fullPath: '/learning-paths/'
      preLoaderRoute: typeof LearningPathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-principals/': {
      id: '/resource-principals/'
      path: '/resource-principals'
      fullPath: '/resource-principals/'
      preLoaderRoute: typeof ResourcePrincipalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-principals/$slug': {
      id: '/resource-principals/$slug'
      path: '/resource-principals/$slug'
      fullPath: '/resource-principals/$slug'
      preLoaderRoute: typeof ResourcePrincipalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinars/': {
      id: '/webinars/'
      path: '/webinars'
      fullPath: '/webinars/'
      preLoaderRoute: typeof WebinarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinars/$slug': {
      id: '/webinars/$slug'
      path: '/webinars/$slug'
      fullPath: '/webinars/$slug'
      preLoaderRoute: typeof WebinarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BecomeAResourcePrincipalRoute: BecomeAResourcePrincipalRoute,
  CertificatesRoute: CertificatesRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  LearningHubRoute: LearningHubRoute,
  MyLearningRoute: MyLearningRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SponsorshipsRoute: SponsorshipsRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  ResourcePrincipalsSlugRoute: ResourcePrincipalsSlugRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
  WebinarsSlugRoute: WebinarsSlugRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ExpertsIndexRoute: ExpertsIndexRoute,
  LearningPathsIndexRoute: LearningPathsIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  ResourcePrincipalsIndexRoute: ResourcePrincipalsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  WebinarsIndexRoute: WebinarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
